language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
install:
  - npm install
  - npm install -g coveralls nyc
script:
  - nyc npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls